apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-gitops-workshop-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: https://github.com/fgauna12/gitops-workshop.git
    targetRevision: HEAD
    kustomize:
      images:
        - 'ghcr.io/fgauna12/front-end=busybox:777'
  destination:
    namespace: "pr-gitops-workshop-1"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
